### ISSUE TITLE
backup failed

### ISSUE THREAD

**Issue by steinliber** [vesoft-inc/nebula-br#26]
I use this to backup nebula data, and it report error below
{"file":"/workspace/pkg/clients/utils.go:19","func":"github.com/vesoft-inc/nebula-br/pkg/clients.connect","level":"info","meta address":"nebula6-metad-2.metad6:9559","msg":"try to connect meta service","time":"2022-01-20T06:52:17.767Z"}
{"file":"/workspace/pkg/clients/utils.go:35","func":"github.com/vesoft-inc/nebula-br/pkg/clients.connect","level":"info","meta address":"nebula6-metad-2.metad6:9559","msg":"connect meta server successfully","time":"2022-01-20T06:52:17.770Z"}
Error: list cluster failed: list cluster nebula6-metad-2.metad6:9559 failed: *meta.ListClusterInfoResp error reading struct: error reading map begin: Invalid data length

look like it doesn't support v2.6.0

**Comment by wey-gu** [comment]
Dear @steinliber,

Sorry, the master head nebula-br is designed for 3.0 + nebula graph only, which will be released in one-month :).

For 2.6.0, please try using the v.0.5.0, while it's not recommended(not released) as in nebula graph 3.0+ nebula-br comes with an agent-based design(to decouple SSH), if possible, it's recommended to use nebula 3.0+ nebula-br master.

Thanks!
