### ISSUE TITLE
panic: download meta data to cluster failed: download meta files from local:///home/nebula/backup/BACKUP_2022_05_19_09_26_45/meta to /usr/local/nebula/data/meta failed: rpc error: code = Unknown desc = source external uri: local:///home/nebula/backup/BACKUP_2022_05_19_09_26_45/meta does not exist

### ISSUE THREAD

**Issue by hunci** [vesoft-inc/nebula-br#39]
/home/nebula/backup/BACKUP_2022_05_19_09_26_45/
backup后上面的目录并没有meta
而是：
BACKUP_2022_05_19_09_26_45.meta  data

br使用github repo编译安装

**Comment by kqzh** [comment]
> /home/nebula/backup/BACKUP_2022_05_19_09_26_45/ backup后上面的目录并没有meta 而是： BACKUP_2022_05_19_09_26_45.meta data
> 
> br使用github repo编译安装

hi, I'm sorry I didn't reply in time, If you back up data to a local disk, only the data of the leader metad is backed up by default. So if there are multiple metad processes, you need to manually copy the directory of the leader metad (path <storage_path>/meta) and overwrite the corresponding directory of other follower meatd processes.

I will close this issue. If there are any problems, you can reopen it
