### ISSUE TITLE
backup rpc error

### ISSUE THREAD

**Issue by robcinko** [vesoft-inc/nebula-br#47]
Hi,

I have problem with nebula backup ./br ends with this error message

`{"level":"fatal","msg":"upload file by agent failed: rpc error: code = Unknown desc = copy from /usr/local/nebula/data/meta/nebula/0/checkpoints/BACKUP_2022_08_08_10_23_43 to /home/ubuntu/BACKUP_2022_08_08_10_23_43/meta error lchown /home/ubuntu/BACKUP_2022_08_08_10_23_43/meta/__disk_parts__.sst: operation not permitted","time":"2022-08-08T10:23:43.735Z"}`

**Comment by wey-gu** [comment]
Does the agent's user have sufficient permission to do the copy between the two paths?

**Comment by robcinko** [comment]
No, that was a problem, after setting up correct permission for agent user backup started working correctly.
Thank you for help

**Comment by wey-gu** [comment]
Thanks to you for playing with NebulaGraph BR and contributing by raising issues. Welcome to the community :).
