### ISSUE TITLE
br for k8s cluster deployments

### ISSUE THREAD

**Issue by klusht** [vesoft-inc/nebula-br#54]
**Describe the bug **
Nebula operator is creating pods that are pulling images without the agent binary.

What pods are supposed to have the agent running 
nebula-metad nebula-graphd nebula-storaged   only ? or also the ones from the operator 

Is bre requiered to run the same command on all nodes ? (same for restore ? )

**Your Environments**
Kuberentes cluster v1.25

**How To Reproduce**
cannot start agetn on nebula PODs as binaries are missing

1. Step 1 : deploy nebula-operator in k8s cluster
3. Step 2: appy nebulaCluster Object
4. Step 3: run br backup from external POD and you will receive 
```
{"file":"./main.go:17","func":"main.main","level":"fatal","msg":"parse cluster response failed: response is not successful, code is E_LIST_CLUSTER_NO_AGENT_FAILURE","time":"2023-01-29T16:27:37.474Z"}
```

**Expected behavior**

agent binaries should be on all container images and start command should start both processes OR embed the agent thread in all cluster services. 

**Additional context**
Is backup and restore enterprise only?
Is there a backup and restore for kubernetes clusters ?

**Comment by kqzh** [comment]
1.  The enterprise version of BR is a superset of the community version of BR. You can still use the community version of BR for full backup and restore
2. backup and restore for kubernetes clusters is not supported now, we are planning to implement this feature
