### ISSUE TITLE
br backup and restore for nebula graph

### ISSUE THREAD

**Issue by klusht** [vesoft-inc/nebula-br#55]
**General Question**
Backup and restore are crucial for any storage solutions and I am confused if this feature is planned to be removed as a default feature. 
Is br under a different license model ? is this feature planned to be exclusive to enterprise edition? 

The available documentation is already using both references (community edition) in the menu title and (enterprise edition) in the notes. 
https://docs.nebula-graph.io/3.3.0/backup-and-restore/nebula-br/2.compile-br/  

Can someone clarify if this is not under the same Apache 2.0 license ?

**Comment by kqzh** [comment]
hi @klusht , the enterprise version of BR is a superset of the community version of BR. You can still use the community version of BR for full backup and restore

**Comment by QingZ11** [comment]
I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
