### ISSUE TITLE
Agent is online but cannot restore

### ISSUE THREAD

**Issue by PNNutkung** [vesoft-inc/nebula-br#56]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

**Nebula Agent is online**  

<img width="917" alt="image" src="https://user-images.githubusercontent.com/9101125/215993524-f178dd5d-46bb-4b41-a2a5-a32191835ee5.png">

Running command:
```
./br backup full --meta "127.0.0.1:9559" --s3.endpoint "*******" --storage "*******" --s3.access_key="*******" --s3.secret_key="*******" --s3.region="*******"
```

Result:
```
{"level":"info","meta address":"127.0.0.1:9559","msg":"Try to connect meta service.","time":"2023-02-01T17:40:50.441Z"}
{"level":"info","meta address":"127.0.0.1:9559","msg":"Connect meta server successfully.","time":"2023-02-01T17:40:50.442Z"}
Error: parse cluster response failed: response is not successful, code is E_LIST_CLUSTER_NO_AGENT_FAILURE
```

**Your Environments (__required__)**

* OS: Linux 5.15.44-1.20220531.el7.x86_64 # 1 SMP Tue May 31 06:52:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Start nubela-agent
2. Run `./br restore full` command

**Expected behavior**
Successfully restore

**Additional context**
Nebula graph 3.0.0
[Nebula BR v0.6.1](https://github.com/vesoft-inc/nebula-br/releases/tag/v0.6.1)
Nebula Agent v0.2.0

**Comment by kqzh** [comment]
hi @PNNutkung , I'm sorry to return your question so late, I have two questions to confirm
1. Can you tell me your cluster topology and whether the services are deployed on a node？
2. Please confirm whether there is an agent service on each cluster node

**Comment by QingZ11** [comment]
I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
