### ISSUE TITLE
agent is not accessible

### ISSUE THREAD

**Issue by mxsavchenko** [vesoft-inc/nebula-br#57]
Nebula version (meta/graph/storage): v3.4.1
Agent version: v3.4.0
BR version: V-3.3.0
OS: AlmaLinux 8.5
Docker version 20.10.10

Hi, i have nebula cluster on 3 different servers in docker containers. On every server run components: meta, graph, storage and agent, each running in its own container. All components communicate with each other through names.
All components are ONLINE:

meta:
> | "metad0" | 9559 | "ONLINE" | "META" | "a6dc673"    | "3.4.1" |
| "metad1" | 9559 | "ONLINE" | "META" | "a6dc673"    | "3.4.1" |
| "metad2" | 9559 | "ONLINE" | "META" | "a6dc673"    | "3.4.1" |

agent:
>| "agentd0"    | 8888 | "ONLINE"  | "AGENT" | "8cf348a"    |         |
| "agentd1"    | 8888 | "ONLINE"  | "AGENT" | "8cf348a"    |         |
| "agentd2"    | 8888 | "ONLINE"  | "AGENT" | "8cf348a"    |         |

graph:
>| "graphd0" | 9669 | "ONLINE" | "GRAPH" | "a6dc673"    | "3.4.1" |
| "graphd1" | 9669 | "ONLINE" | "GRAPH" | "a6dc673"    | "3.4.1" |
| "graphd2" | 9669 | "ONLINE" | "GRAPH" | "a6dc673"    | "3.4.1" |

storage:
>| "storaged0" | 9779 | "ONLINE" | "STORAGE" | "a6dc673"    | "3.4.1" |
| "storaged1" | 9779 | "ONLINE" | "STORAGE" | "a6dc673"    | "3.4.1" |
| "storaged2" | 9779 | "ONLINE" | "STORAGE" | "a6dc673"    | "3.4.1" |

but when trying to make a backup, an error appears:
>./br backup full --debug --meta "metad0:9559" --storage "local:///tmp/backup"
>{"file":"github.com/vesoft-inc/nebula-br/pkg/storage/flags.go:93","func":"github.com/vesoft-inc/nebula-br/pkg/storage.ParseFromFlags","level":"debug","msg":"Parse storage flag.","time":"2023-03-23T03:58:07.500Z","type":1,"uri":"local:///tmp/backup"}
{"file":"github.com/vesoft-inc/nebula-br/pkg/clients/utils.go:20","func":"github.com/vesoft-inc/nebula-br/pkg/clients.connect","level":"info","meta address":"metad0:9559","msg":"Try to connect meta service.","time":"2023-03-23T03:58:07.500Z"}
{"file":"github.com/vesoft-inc/nebula-br/pkg/clients/utils.go:44","func":"github.com/vesoft-inc/nebula-br/pkg/clients.connect","level":"info","meta address":"metad0:9559","msg":"Connect meta server successfully.","time":"2023-03-23T03:58:07.501Z"}
{"file":"github.com/vesoft-inc/nebula-agent@v0.1.1/pkg/storage/storage.go:50","func":"github.com/vesoft-inc/nebula-agent/pkg/storage.New","level":"debug","msg":"Create type: Local storage.","time":"2023-03-23T03:58:07.503Z","uri":"local:///tmp/backup"}

In meta logs i see also errors:
>I20230323 08:58:23.577836   156 ListClusterInfoProcessor.cpp:135] There is no other service than agent in host: agentd0
I20230323 08:58:23.577855   156 ListClusterInfoProcessor.cpp:128] There is no agent in host graphd1

**Comment by wey-gu** [comment]
@kqzh was the adaptation towards containerized finished, please?

**Comment by wey-gu** [comment]
@mxsavchenko sorry, the docker-compose is not for production, in k8s operator, the br is ready now.

please refer to https://docs.nebula-graph.io/3.4.1/nebula-operator/10.backup-restore-using-operator/

**Comment by mxsavchenko** [comment]
do you have a plan to complete the adaptation for docker-compose?

> @mxsavchenko sorry, the docker-compose is not for production, in k8s operator, the br is ready now.
> 
> please refer to https://docs.nebula-graph.io/3.4.1/nebula-operator/10.backup-restore-using-operator/

thank,
do you have a plan to complete the adaptation for docker-compose?

**Comment by QingZ11** [comment]
I have noticed that the issue you created hasn’t been updated for nearly a month, so I have to close it for now. If you have any new updates, you are welcome to reopen this issue anytime.

Thanks a lot for your contribution anyway 😊
