### ISSUE TITLE
BR: in production, ssh to a VM is prohibited, could BR be decoupled with SSH?

### ISSUE THREAD

**Issue by chaselwin** [vesoft-inc/nebula-br#6]
出于安全考虑，线上虚机禁止ssh登录。BR工具无法绕过ssh免密登录或者通过其它方式进行指定图空间备份？

**Comment by wey-gu** [comment]
Dear @chaselwin,
Thanks for raising ISSUES in the nebula community(welcome!), I transferred the issue here in nebula-br repo and translated the title into English.

@monadbobo could help provide more information on this.(thanks :) )

**Comment by monadbobo** [comment]
Hi, for the time being the BR tool forces SSH login.

**Comment by linkensphere201** [comment]
I'll close this issue. Please, reopen or create a new one if you encounter more problems. @chaselwin

**Comment by wey-gu** [comment]
Hopefully, we could soon decouple SSH :)

https://discuss.nebula-graph.com.cn/t/topic/4872/4
