### ISSUE TITLE
Where can I find the license file?

### ISSUE THREAD

**Issue by BabyQiPuppy** [vesoft-inc/nebula-br#65]
**General Question**

**Comment by kqzh** [comment]
hi @BabyQiPuppy , nebula-br is public, don't need license

**Comment by fredgan** [comment]
Hi @kqzh , sorry, I don't think so. As to the definition of Open Source Software(OSS) from [OSI](https://opensource.org/osd)，

> Open source doesn’t just mean access to the source code. The distribution terms of open source software must comply with the following criteria

The criteria is described by Open Source License. So, if this project has no declared License, this software cannot be called Open Source Software. User don't know how to follow the criteria.

I recommend a License file should be added in the root, or claim a License statement in the README file at least. Just like you have chosen the Apache License 2.0 in [nebula project](https://github.com/vesoft-inc/nebula/blob/master/LICENSE).

**Comment by kqzh** [comment]
> Hi @kqzh , sorry, I don't think so. As to the definition of Open Source Software(OSS) from [OSI](https://opensource.org/osd)，
> 
> > Open source doesn’t just mean access to the source code. The distribution terms of open source software must comply with the following criteria
> 
> The criteria is described by Open Source License. So, if this project has no declared License, this software cannot be called Open Source Software. User don't know how to follow the criteria.
> 
> I recommend a License file should be added in the root, or claim a License statement in the README file at least. Just like you have chosen the Apache License 2.0 in [nebula project](https://github.com/vesoft-inc/nebula/blob/master/LICENSE).

got it, thank you for your reminding
